"use client"

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

// Типы языков
export type Language = 'ru' | 'kk'

// Словарь переводов
export const translations = {
    ru: {
        // Навигация
        nav: {
            home: 'Главная',
            explore: 'Поиск',
            trending: 'Тренды',
            bookmarks: 'Закладки',
            notifications: 'Уведомления',
            profile: 'Профиль',
            settings: 'Настройки',
            create: 'Создать',
            login: 'Войти',
            register: 'Регистрация',
            logout: 'Выйти',
            search: 'Поиск...',
        },
        // Общие
        common: {
            loading: 'Загрузка...',
            error: 'Ошибка',
            save: 'Сохранить',
            cancel: 'Отмена',
            delete: 'Удалить',
            edit: 'Редактировать',
            share: 'Поделиться',
            copy: 'Копировать',
            copied: 'Скопировано!',
            viewAll: 'Смотреть все',
            showMore: 'Показать ещё',
            showLess: 'Скрыть',
            noResults: 'Ничего не найдено',
            posts: 'Постам',
            likes: 'Лайкам',
            views: 'Просмотрам',
            comments: 'Комментариям',
            recent: 'Недавние',
            popular: 'Популярные',
            all: 'Все',
            today: 'Сегодня',
            thisWeek: 'За неделю',
            thisMonth: 'За месяц',
            language: 'Язык',
            features: 'Возможности',
        },
        // Авторизация
        auth: {
            welcomeBack: 'С возвращением!',
            loginSubtitle: 'Войдите в свой аккаунт GitForum',
            createAccount: 'Создать аккаунт',
            registerSubtitle: 'Присоединяйтесь к сообществу разработчиков',
            email: 'Email',
            password: 'Пароль',
            confirmPassword: 'Подтвердите пароль',
            username: 'Имя пользователя',
            displayName: 'Отображаемое имя',
            rememberMe: 'Запомнить меня',
            forgotPassword: 'Забыли пароль?',
            noAccount: 'Нет аккаунта?',
            hasAccount: 'Уже есть аккаунт?',
            signIn: 'Войти',
            signUp: 'Зарегистрироваться',
            orContinueWith: 'или войти через',
            termsAgree: 'Регистрируясь, вы соглашаетесь с',
            termsOfService: 'Условиями использования',
            and: 'и',
            privacyPolicy: 'Политикой конфиденциальности',
        },
        // Страница Explore
        explore: {
            title: 'Поиск',
            subtitle: 'Найдите лучшие сниппеты кода',
            searchPlaceholder: 'Поиск по названию, описанию, тегам...',
            allLanguages: 'Все языки',
            allTags: 'Все теги',
            sortBy: 'Сортировка',
            trending: 'Трендовые',
            newToday: 'Новые сегодня',
            thisWeekPosts: 'За неделю',
        },
        // Страница Tags
        tags: {
            title: 'Теги',
            subtitle: 'Исследуйте темы и технологии',
            searchPlaceholder: 'Поиск тегов...',
            popular: 'Популярные',
            alphabetical: 'По алфавиту',
            recentlyUsed: 'Недавно использованные',
            postsCount: 'постов',
        },
        // Страница Bookmarks
        bookmarks: {
            title: 'Закладки',
            subtitle: 'Сохранённые сниппеты',
            empty: 'Нет закладок',
            emptySubtitle: 'Сохраняйте интересные сниппеты, чтобы вернуться к ним позже',
            explore: 'Найти сниппеты',
            remove: 'Удалить из закладок',
            removed: 'Убрано из закладок',
            loading: 'Загрузка закладок...',
            loadError: 'Ошибка загрузки закладок',
            noDescription: 'Нет описания',
            error: 'Ошибка',
            bookmarksCount: 'Закладок',
            likesCount: 'Лайков',
            topLanguage: 'Топ язык',
            searchPlaceholder: 'Поиск закладок...',
            allLanguages: 'Все языки',
            byDate: 'По дате',
            byLikes: 'По лайкам',
            byTitle: 'По названию',
            found: 'Найдено',
            nothingFound: 'Ничего не найдено',
        },
        // Страница Trending
        trending: {
            title: 'Тренды',
            subtitle: 'Популярные сниппеты',
            hot: 'HOT',
            searchPlaceholder: 'Поиск в трендах...',
        },
        // Страница Notifications
        notifications: {
            title: 'Уведомления',
            allRead: 'Всё прочитано',
            unread: 'непрочитанных',
            markAllRead: 'Прочитать все',
            empty: 'Нет уведомлений',
            emptySubtitle: 'Здесь будут появляться уведомления о лайках, комментариях и подписках',
            liked: 'лайкнул(-а) ваш пост',
            commented: 'прокомментировал(-а) ваш пост',
            followed: 'подписался(-ась) на вас',
            mentioned: 'упомянул(-а) вас',
            replied: 'ответил(-а) на ваш комментарий',
            newPost: 'опубликовал(-а) новый пост',
            loading: 'Загрузка...',
            allMarkedRead: 'Все уведомления прочитаны',
            updateError: 'Ошибка при обновлении',
            explorePosts: 'Исследовать посты',
            total: 'Всего',
            unreadCount: 'Непрочитанных',
            today: 'Сегодня',
            justNow: 'только что',
        },
        // Страница Profile
        profile: {
            title: 'Профиль',
            editProfile: 'Редактировать',
            posts: 'Посты',
            followers: 'Подписчики',
            following: 'Подписки',
            joined: 'Присоединился',
            noPosts: 'Пока нет постов',
            createFirst: 'Создайте свой первый сниппет',
            createPost: 'Создать пост',
        },
        // Страница Settings
        settings: {
            title: 'Настройки',
            subtitle: 'Управление аккаунтом и предпочтениями',
            tabs: {
                profile: 'Профиль',
                appearance: 'Внешний вид',
                notifications: 'Уведомления',
                account: 'Аккаунт',
            },
            // Профиль
            profilePhoto: 'Фото профиля',
            photoHint: 'JPG, PNG или GIF. Максимум 2MB.',
            removePhoto: 'Удалить фото',
            displayName: 'Отображаемое имя',
            username: 'Имя пользователя',
            usernameHint: 'Имя пользователя изменить нельзя',
            emailHint: 'Email изменить нельзя',
            bio: 'О себе',
            bioPlaceholder: 'Расскажите о себе...',
            characters: 'символов',
            location: 'Местоположение',
            website: 'Веб-сайт',
            github: 'GitHub',
            profileSaved: 'Профиль сохранён!',
            // Внешний вид
            interfaceLanguage: 'Язык интерфейса',
            chooseLanguage: 'Выберите предпочитаемый язык',
            theme: 'Тема оформления',
            chooseTheme: 'Выберите цветовую схему',
            themeLight: 'Светлая',
            themeDark: 'Тёмная',
            themeSystem: 'Системная',
            codeTheme: 'Тема кода',
            codeThemeHint: 'Подсветка синтаксиса для блоков кода',
            codeFont: 'Шрифт кода',
            codeFontHint: 'Шрифт для отображения кода',
            fontSize: 'Размер шрифта',
            fontSizeHint: 'Размер шрифта в редакторе кода',
            preview: 'Предпросмотр',
            lineNumbers: 'Номера строк',
            lineNumbersHint: 'Показывать номера строк в коде',
            wordWrap: 'Перенос строк',
            wordWrapHint: 'Переносить длинные строки кода',
            compactMode: 'Компактный режим',
            compactModeHint: 'Уменьшить отступы для большего контента',
            saveSettings: 'Сохранить настройки',
            settingsSaved: 'Настройки сохранены!',
            // Уведомления
            emailNotifications: 'Email уведомления',
            pushNotifications: 'Push уведомления',
            enableAll: 'Вкл. все',
            disableAll: 'Выкл. все',
            notifyLikes: 'Лайки',
            notifyLikesHint: 'Когда кто-то лайкнул ваш пост',
            notifyComments: 'Комментарии',
            notifyCommentsHint: 'Когда кто-то оставил комментарий',
            notifyFollowers: 'Новые подписчики',
            notifyFollowersHint: 'Когда кто-то подписался на вас',
            notifyMentions: 'Упоминания',
            notifyMentionsHint: 'Когда вас упомянули',
            notifyDigest: 'Еженедельный дайджест',
            notifyDigestHint: 'Подборка лучших постов за неделю',
            notificationsSaved: 'Настройки уведомлений сохранены!',
            // Аккаунт
            changePassword: 'Смена пароля',
            currentPassword: 'Текущий пароль',
            newPassword: 'Новый пароль',
            confirmNewPassword: 'Подтвердите пароль',
            passwordsMatch: 'Пароли совпадают',
            passwordStrength: {
                weak: 'Слабый',
                fair: 'Средний',
                good: 'Хороший',
                strong: 'Сильный',
                veryStrong: 'Очень сильный',
            },
            passwordRequirements: {
                minLength: 'Минимум 8 символов',
                uppercase: 'Одна заглавная буква',
                lowercase: 'Одна строчная буква',
                number: 'Одна цифра',
                special: 'Один спецсимвол',
            },
            updatePassword: 'Сменить пароль',
            passwordUpdated: 'Пароль успешно изменён!',
            twoFactorAuth: 'Двухфакторная аутентификация',
            twoFactorHint: 'Добавьте дополнительный уровень безопасности к вашему аккаунту.',
            enable2FA: 'Включить 2FA',
            sessions: 'Сессии',
            logoutAll: 'Выйти со всех устройств',
            logoutAllHint: 'Выйти из аккаунта на всех устройствах.',
            exportData: 'Экспорт данных',
            exportDataHint: 'Скачайте копию ваших данных: профиль, закладки и посты.',
            exportButton: 'Экспорт данных',
            exported: 'Данные экспортированы!',
            dangerZone: 'Опасная зона',
            deleteAccount: 'Удаление аккаунта',
            deleteAccountHint: 'После удаления аккаунта все ваши данные будут безвозвратно удалены.',
            deleteAccountButton: 'Удалить аккаунт',
            deleteConfirmTitle: 'Вы уверены?',
            deleteConfirmText: 'Это действие нельзя отменить. Все ваши данные, посты и закладки будут удалены навсегда.',
        },
        // Widgets
        widgets: {
            trendingNow: 'Сейчас в тренде',
            topContributors: 'Лучшие авторы',
            viewProfile: 'Профиль',
            quickActions: 'Быстрые действия',
            newSnippet: 'Новый сниппет',
            community: 'Сообщество',
            statistics: 'Статистика',
            totalLikes: 'Всего лайков',
            commentsCount: 'Комментариев',
            viewsCount: 'Просмотров',
            viewAll: 'Все',
            aboutUs: 'О нас',
            terms: 'Условия',
            privacy: 'Приватность',
            help: 'Помощь',
        },
        // Создание поста
        newPost: {
            title: 'Новый пост',
            subtitle: 'Поделитесь кодом с сообществом',
            titleLabel: 'Заголовок',
            titlePlaceholder: 'Например: Кастомный React хук для debounce',
            descriptionLabel: 'Описание',
            descriptionPlaceholder: 'Кратко опишите, что делает ваш код...',
            languageLabel: 'Язык',
            selectLanguage: 'Выберите язык',
            filenameLabel: 'Имя файла',
            filenamePlaceholder: 'Например: useDebounce.ts',
            codeLabel: 'Код',
            editor: 'Редактор',
            preview: 'Превью',
            previewPlaceholder: '// Превью появится здесь...',
            codePlaceholder: '// Вставьте ваш код здесь...',
            tagsLabel: 'Теги',
            tagsMax: 'макс. 5',
            addTagPlaceholder: 'Добавьте теги (Enter для добавления)',
            suggestions: 'Предложения:',
            public: 'Публичный',
            private: 'Приватный',
            draft: 'Черновик',
            draftSaved: 'Черновик сохранён',
            publish: 'Опубликовать',
            publishing: 'Публикация...',
            create: 'Создать',
            published: 'Пост опубликован!',
            loginRequired: 'Войдите в аккаунт',
        },
        // Лента
        feed: {
            title: 'Лента',
            subtitle: 'Свежие публикации',
            refresh: 'Обновить',
            loadingPosts: 'Загрузка постов...',
            tryAgain: 'Попробовать снова',
            noPosts: 'Пока нет постов',
            beFirst: 'Станьте первым, кто поделится кодом с сообществом!',
            createPost: 'Создать пост',
            showMore: 'Показать ещё',
            loading: 'Загрузка...',
        },
        // Поиск
        search: {
            users: 'Пользователи',
            posts: 'Посты',
            noResults: 'Ничего не найдено',
        },
        // Валидация
        validation: {
            required: 'обязательны',
            minChars: 'Минимум 3 символа',
            onlyLatinAndUnderscore: 'Только буквы, цифры и _',
            invalidEmail: 'Некорректный email',
            passwordNotMeet: 'Пароль не соответствует требованиям',
            acceptTerms: 'Необходимо принять условия',
            enterTitle: 'Введите заголовок',
            enterFilename: 'Введите имя файла',
            selectLanguage: 'Выберите язык',
            enterCode: 'Введите код',
            loginError: 'Ошибка входа',
            accountCreated: 'Аккаунт создан!',
            commentEmpty: 'Комментарий не может быть пустым',
            loginToComment: 'Войдите, чтобы оставить комментарий',
            commentAdded: 'Комментарий добавлен!',
            commentAddError: 'Ошибка добавления комментария',
            replyAdded: 'Ответ добавлен!',
            replyError: 'Ошибка отправки ответа',
            commentDeleted: 'Комментарий удалён',
            deleteError: 'Ошибка удаления',
        },
        // Дополнительные элементы футера/навигации
        footer: {
            about: 'О нас',
            privacy: 'Конфиденциальность',
            terms: 'Условия',
            contact: 'Контакты',
            help: 'Помощь',
            copyright: '© 2025 GitForum',
        },
        // Floating badges на лендинге
        badges: {
            fast: 'Быстро',
            secure: 'Безопасно',
            modern: 'Современно',
            live: 'Live',
            ready: 'Готово',
            secureLogin: 'Безопасный вход',
            freeRegistration: 'Бесплатная регистрация',
            haveAccount: 'Уже есть аккаунт?',
            instantAuth: 'Мгновенная авторизация',
            secureEncryption: 'Безопасное шифрование',
            oauthIntegration: 'OAuth 2.0 интеграция',
            createProfile: 'Создайте профиль',
            chooseUsername: 'Выберите уникальный username',
            shareCode: 'Делитесь кодом',
            publishSnippets: 'Публикуйте сниппеты',
            communicate: 'Общайтесь',
            findLikeminded: 'Находите единомышленников',
            programmingLanguages: 'языков программирования',
        },
        // Комментарии
        comments: {
            title: 'Комментарии',
            reply: 'Ответить',
            delete: 'Удалить',
            cancel: 'Отмена',
            send: 'Отправить',
            writePlaceholder: 'Напишите комментарий...',
            replyTo: 'Ответить',
            noneYet: 'Пока нет комментариев',
            beFirst: 'Будьте первым!',
            loginPrompt: 'Войдите, чтобы оставить комментарий',
            login: 'Войти',
        },
        // Фильтры explore
        filters: {
            searchPlaceholder: 'Поиск сниппетов, тегов...',
            activeTags: 'Активные теги:',
            clear: 'Очистить',
            tags: 'Теги',
            categories: 'Категории',
            period: 'Период',
            sort: 'Сортировка',
            today: 'Сегодня',
            week: 'Неделя',
            month: 'Месяц',
            allTime: 'Всё время',
            byLikes: 'По лайкам',
            byComments: 'По комментариям',
            byViews: 'По просмотрам',
            recent: 'Новые',
            all: 'Все',
        },
        // Пост
        post: {
            by: 'от',
            copyCode: 'Копировать код',
            codeCopied: 'Код скопирован!',
            comments: 'Комментарии',
            addComment: 'Написать комментарий...',
            sendComment: 'Отправить',
            noComments: 'Пока нет комментариев',
            beFirst: 'Будьте первым, кто оставит комментарий!',
            deleteComment: 'Удалить комментарий',
            editComment: 'Редактировать',
        },
        // Время
        time: {
            justNow: 'только что',
            minutesAgo: 'м назад',
            hoursAgo: 'ч назад',
            daysAgo: 'д назад',
        },
        // Начальная страница
        landing: {
            tagline: 'Делитесь кодом, а не скриншотами',
            heroTitle: 'Открытый форум',
            heroTitleHighlight: 'обмена кодом',
            heroDescription: 'Делитесь красивыми сниппетами кода, находите трендовые решения и общайтесь с разработчиками по всему миру. Никаких скриншотов — только чистый код с подсветкой синтаксиса.',
            getStarted: 'Начать бесплатно',
            features: {
                title: 'Всё для работы с кодом',
                subtitle: 'Создано разработчиками для разработчиков. Все инструменты в одном месте.',
                syntaxHighlighting: 'Подсветка синтаксиса',
                syntaxHighlightingDesc: 'Красивый рендеринг кода с темами VS Code для 10+ языков',
                trendingSnippets: 'Трендовые сниппеты',
                trendingSnippetsDesc: 'Находите самые популярные сниппеты в сообществе',
                smartTags: 'Умные теги',
                smartTagsDesc: 'Организуйте и ищите код по языку, фреймворку или теме',
                bookmarks: 'Закладки',
                bookmarksDesc: 'Сохраняйте любимые сниппеты для быстрого доступа',
                easySharing: 'Простой шеринг',
                easySharingDesc: 'Делитесь кодом одним кликом, без скриншотов',
                powerfulSearch: 'Мощный поиск',
                powerfulSearchDesc: 'Находите нужное с помощью продвинутого поиска',
            },
            howItWorks: {
                title: 'Как это работает',
                subtitle: 'Три простых шага для публикации кода',
                step1: 'Создайте',
                step1Desc: 'Напишите или вставьте код с полной подсветкой синтаксиса',
                step2: 'Поделитесь',
                step2Desc: 'Опубликуйте сниппет и поделитесь с сообществом',
                step3: 'Исследуйте',
                step3Desc: 'Изучайте тренды, учитесь у других и растите вместе',
            },
            stats: {
                developers: 'Разработчиков',
                snippets: 'Сниппетов кода',
                languages: 'Языков',
                linesShared: 'Строк опубликовано',
            },
            cta: {
                joinDevelopers: 'Присоединяйтесь к форуму разработчиков',
                readyToShare: 'Готовы делиться кодом?',
                signUpToday: 'Зарегистрируйтесь сегодня и начните публиковать красивые сниппеты.',
                createAccount: 'Создать бесплатный аккаунт',
            },
            footer: {
                about: 'О нас',
                privacy: 'Конфиденциальность',
                terms: 'Условия',
                contact: 'Контакты',
                copyright: '© 2025 GitForum. Все права защищены.',
            },
        },
        // Страница настроек
        settingsPage: {
            // Account
            changePassword: 'Смена пароля',
            updateAccountPassword: 'Обновите пароль аккаунта',
            currentPassword: 'Текущий пароль',
            newPassword: 'Новый пароль',
            confirmPassword: 'Подтвердите пароль',
            passwordsMatch: 'Пароли совпадают',
            enterCurrentPassword: 'Введите текущий пароль',
            enterNewPassword: 'Введите новый пароль',
            confirmPasswordRequired: 'Подтвердите пароль',
            passwordsDontMatch: 'Пароли не совпадают',
            minChars: 'Минимум 8 символов',
            fixErrors: 'Исправьте ошибки',
            passwordChanged: 'Пароль изменён!',
            checkCurrentPassword: 'Проверьте текущий пароль',
            saving: 'Сохранение...',
            changePasswordBtn: 'Сменить пароль',
            // Password strength
            weak: 'Слабый',
            medium: 'Средний',
            good: 'Хороший',
            strong: 'Сильный',
            veryStrong: 'Очень сильный',
            min8chars: 'Минимум 8 символов',
            uppercase: 'Заглавная буква',
            lowercase: 'Строчная буква',
            digit: 'Цифра',
            special: 'Спецсимвол',
            // 2FA
            twoFactor: 'Двухфакторная аутентификация',
            additionalSecurity: 'Дополнительная защита',
            twoFactorDesc: 'Добавьте дополнительный уровень безопасности.',
            enable2FA: 'Включить 2FA',
            twoFactorFuture: '2FA будет доступна в будущих обновлениях',
            // Connected accounts
            connectedAccounts: 'Привязанные аккаунты',
            oauthProviders: 'OAuth провайдеры',
            notConnected: 'Не подключено',
            disconnect: 'Отключить',
            connect: 'Подключить',
            disconnected: 'отключен',
            disconnectError: 'Ошибка отключения',
            disconnectAccountError: 'Ошибка при отключении аккаунта',
            // Sessions
            sessions: 'Сессии',
            sessionManagement: 'Управление входом',
            logoutAllDesc: 'Выйти из аккаунта на всех устройствах.',
            logoutAllDevices: 'Выйти со всех устройств',
            loggedOutAll: 'Вы вышли со всех устройств',
            logoutError: 'Ошибка при выходе',
            // Export
            exportData: 'Экспорт данных',
            downloadDataCopy: 'Скачайте копию данных',
            exporting: 'Экспортируем...',
            exportDataBtn: 'Экспорт данных',
            dataExported: 'Данные экспортированы!',
            exportError: 'Ошибка экспорта',
            // Danger zone
            dangerZone: 'Опасная зона',
            irreversibleActions: 'Необратимые действия',
            deleteAccountWarning: 'После удаления аккаунта все данные будут удалены безвозвратно.',
            deleteAccount: 'Удалить аккаунт',
            areYouSure: 'Вы уверены?',
            deleteConfirmation: 'Это действие нельзя отменить. Все данные будут удалены навсегда.',
            cancel: 'Отмена',
            deleteFuture: 'Удаление аккаунта будет доступно в будущих обновлениях',
            // Appearance
            interfaceLanguage: 'Язык интерфейса',
            selectPreferredLanguage: 'Выберите предпочитаемый язык',
            codeTheme: 'Тема кода',
            syntaxHighlighting: 'Подсветка синтаксиса',
            codeFont: 'Шрифт кода',
            monospacedFont: 'Моноширинный шрифт',
            fontSize: 'Размер шрифта',
            fontSizeInCode: 'Размер текста в коде',
            lineHeight: 'Межстрочный интервал',
            spaceBetweenLines: 'Отступ между строками',
            compact: 'Компактно',
            spacious: 'Просторно',
            editorSettings: 'Настройки редактора',
            additionalOptions: 'Дополнительные опции',
            lineNumbers: 'Номера строк',
            leftOfCode: 'Слева от кода',
            wordWrap: 'Перенос строк',
            autoWrap: 'Автоматический перенос',
            preview: 'Предпросмотр',
            codePreview: 'Как будет выглядеть код',
            settingsSaved: 'Настройки сохранены!',
            saveSettings: 'Сохранить настройки',
            // Notifications
            emailNotifications: 'Email уведомления',
            notificationsToEmail: 'Уведомления на почту',
            pushNotifications: 'Push уведомления',
            browserNotifications: 'Уведомления в браузере',
            on: 'Вкл',
            off: 'Выкл',
            likes: 'Лайки',
            whenLiked: 'Когда кто-то лайкнул ваш пост',
            comments: 'Комментарии',
            whenCommented: 'Когда кто-то оставил комментарий',
            newFollowers: 'Новые подписчики',
            whenFollowed: 'Когда кто-то подписался на вас',
            mentions: 'Упоминания',
            whenMentioned: 'Когда вас упомянули',
            weeklyDigest: 'Еженедельный дайджест',
            weeklyDigestDesc: 'Подборка лучших постов за неделю',
            notificationsSaved: 'Настройки уведомлений сохранены!',
            // Profile
            profilePhoto: 'Фото профиля',
            photoFormats: 'JPG, PNG или GIF. Максимум 5MB.',
            cancelUpload: 'Отменить',
            displayName: 'Отображаемое имя',
            username: 'Имя пользователя',
            cannotChange: 'Изменить нельзя',
            aboutMe: 'О себе',
            tellAboutYourself: 'Расскажите о себе...',
            location: 'Местоположение',
            cityCountry: 'Город, Страна',
            website: 'Веб-сайт',
            nameRequired: 'Имя обязательно',
            bioMaxLength: 'Био должно быть не более 160 символов',
            urlFormat: 'URL должен начинаться с http:// или https://',
            fixErrorsBeforeSave: 'Исправьте ошибки перед сохранением',
            profileSaved: 'Профиль сохранён!',
            profileSaveError: 'Ошибка сохранения профиля',
            saveChanges: 'Сохранить изменения',
            uploadingAvatar: 'Загрузка аватара...',
            avatarUpdated: 'Аватар обновлён!',
            fileTooLarge: 'Файл слишком большой. Максимум 5MB.',
            selectImage: 'Выберите изображение (JPG, PNG, GIF, WebP)',
            avatarUploadError: 'Ошибка загрузки аватара',
        },
        // Тексты страниц
        pages: {
            // Settings page
            settings: {
                title: 'Настройки',
                subtitle: 'Управление аккаунтом и предпочтениями',
                tabDescriptions: {
                    profile: 'Имя, аватар, био',
                    appearance: 'Тема, язык',
                    notifications: 'Email, push',
                    account: 'Пароль, безопасность',
                },
            },
            // Trending page
            trending: {
                howItWorks: 'Как это работает',
                howItWorksDesc: 'Посты ранжируются по популярности — количество лайков, комментариев и просмотров. Посты с пометкой HOT имеют высокую активность.',
                searchPlaceholder: 'Поиск в трендах...',
                loadingTrends: 'Загрузка трендов...',
                loadError: 'Ошибка загрузки',
                noTrendingPosts: 'Нет trending постов',
                createFirstPost: 'Создайте первый пост!',
                changeFilters: 'Попробуйте изменить фильтры',
                found: 'Найдено',
                posts: 'Постов',
                likes: 'Лайков',
                views: 'Просмотров',
                noDescription: 'Нет описания',
            },
            // Tags page
            tags: {
                totalTags: 'Всего тегов',
                totalPosts: 'Всего постов',
                topTag: 'Топ тег',
                popularTags: 'Популярные теги',
                loadingTags: 'Загрузка тегов...',
                found: 'Найдено',
                tryAnotherSearch: 'Попробуйте изменить поисковый запрос',
            },
            // Explore page
            explore: {
                noDescription: 'Нет описания',
                errorLoading: 'Ошибка загрузки данных',
                loading: 'Загрузка...',
                nothingFound: 'Ничего не найдено',
                noPosts: 'Пока нет постов. Будьте первым!',
                tryChangeFilters: 'Попробуйте изменить фильтры или поисковый запрос',
                found: 'Найдено',
                thisWeek: 'За неделю',
                today: 'Сегодня',
            },
            // Post page
            post: {
                loadingPost: 'Загрузка поста...',
                postNotFound: 'Пост не найден',
                maybeDeleted: 'Возможно, он был удалён',
                back: 'Вернуться',
                backToFeed: 'Назад в ленту',
                edit: 'Изменить',
                delete: 'Удалить',
                codeCopied: 'Код скопирован!',
                linkCopied: 'Ссылка скопирована!',
                loginToLike: 'Войдите, чтобы лайкнуть',
                loginToBookmark: 'Войдите, чтобы сохранить',
                removedFromBookmarks: 'Убрано из закладок',
                addedToBookmarks: 'Добавлено в закладки',
                postDeleted: 'Пост удалён',
                deleteError: 'Ошибка удаления',
                copied: 'Скопировано',
                copy: 'Копировать',
                error: 'Ошибка',
                minutesAgo: 'мин назад',
                hoursAgo: 'ч назад',
                daysAgo: 'дн назад',
            },
            // Profile page
            profile: {
                share: 'Поделиться',
                settings: 'Настройки',
                linkCopied: 'Ссылка скопирована!',
                joined: 'С',
                posts: 'Постов',
                followers: 'Подписчиков',
                following: 'Подписки',
                likes: 'Лайков',
                views: 'Просмотров',
                postsTab: 'Посты',
                bookmarksTab: 'Закладки',
                noDescription: 'Нет описания',
                noPosts: 'Пока нет постов',
                createFirstSnippet: 'Создайте свой первый сниппет и поделитесь кодом с сообществом',
                createPost: 'Создать пост',
                noBookmarks: 'Нет закладок',
                saveSnippets: 'Сохраняйте полезные сниппеты для быстрого доступа',
                findSnippets: 'Найти сниппеты',
                loading: 'Загрузка...',
            },
            // User page
            user: {
                userNotFound: 'Пользователь не найден',
                backToFeed: 'Вернуться',
                follow: 'Подписаться',
                unfollow: 'Отписаться',
                message: 'Сообщение',
                share: 'Поделиться',
                report: 'Пожаловаться',
                joined: 'С',
                posts: 'Постов',
                followers: 'Подписчиков',
                following: 'Подписки',
                likes: 'Лайков',
                views: 'Просмотров',
                postsTab: 'Посты',
                noPosts: 'Пока нет постов',
                userHasNoPosts: 'Пользователь пока не опубликовал ни одного поста',
                noDescription: 'Нет описания',
                loading: 'Загрузка...',
                settings: 'Настройки',
            },
        },
    },
    kk: {
        // Навигация
        nav: {
            home: 'Басты бет',
            explore: 'Іздеу',
            trending: 'Трендтер',
            bookmarks: 'Бетбелгілер',
            notifications: 'Хабарламалар',
            profile: 'Профиль',
            settings: 'Баптаулар',
            create: 'Жасау',
            login: 'Кіру',
            register: 'Тіркелу',
            logout: 'Шығу',
            search: 'Іздеу...',
        },
        // Общие
        common: {
            loading: 'Жүктелуде...',
            error: 'Қате',
            save: 'Сақтау',
            cancel: 'Болдырмау',
            delete: 'Жою',
            edit: 'Өңдеу',
            share: 'Бөлісу',
            copy: 'Көшіру',
            copied: 'Көшірілді!',
            viewAll: 'Барлығын көру',
            showMore: 'Көбірек көрсету',
            showLess: 'Жасыру',
            noResults: 'Ештеңе табылмады',
            posts: 'Посттар',
            likes: 'Лайктар',
            views: 'Қаралымдар',
            comments: 'Пікірлер',
            recent: 'Соңғы',
            popular: 'Танымал',
            all: 'Барлығы',
            today: 'Бүгін',
            thisWeek: 'Осы апта',
            thisMonth: 'Осы ай',
            language: 'Тіл',
            features: 'Мүмкіндіктер',
        },
        // Авторизация
        auth: {
            welcomeBack: 'Қош келдіңіз!',
            loginSubtitle: 'GitForum аккаунтыңызға кіріңіз',
            createAccount: 'Аккаунт жасау',
            registerSubtitle: 'Әзірлеушілер қауымдастығына қосылыңыз',
            email: 'Email',
            password: 'Құпия сөз',
            confirmPassword: 'Құпия сөзді растаңыз',
            username: 'Пайдаланушы аты',
            displayName: 'Көрсетілетін ат',
            rememberMe: 'Мені есте сақта',
            forgotPassword: 'Құпия сөзді ұмыттыңыз ба?',
            noAccount: 'Аккаунтыңыз жоқ па?',
            hasAccount: 'Аккаунтыңыз бар ма?',
            signIn: 'Кіру',
            signUp: 'Тіркелу',
            orContinueWith: 'немесе арқылы кіру',
            termsAgree: 'Тіркелу арқылы сіз келесілермен келісесіз:',
            termsOfService: 'Қызмет көрсету шарттары',
            and: 'және',
            privacyPolicy: 'Құпиялылық саясаты',
        },
        // Страница Explore
        explore: {
            title: 'Іздеу',
            subtitle: 'Ең жақсы код үзінділерін табыңыз',
            searchPlaceholder: 'Атауы, сипаттамасы, тегтері бойынша іздеу...',
            allLanguages: 'Барлық тілдер',
            allTags: 'Барлық тегтер',
            sortBy: 'Сұрыптау',
            trending: 'Трендтегі',
            newToday: 'Бүгінгі жаңалар',
            thisWeekPosts: 'Осы аптада',
        },
        // Страница Tags
        tags: {
            title: 'Тегтер',
            subtitle: 'Тақырыптар мен технологияларды зерттеңіз',
            searchPlaceholder: 'Тегтерді іздеу...',
            popular: 'Танымал',
            alphabetical: 'Әліпби бойынша',
            recentlyUsed: 'Жақында қолданылған',
            postsCount: 'пост',
        },
        // Страница Bookmarks
        bookmarks: {
            title: 'Бетбелгілер',
            subtitle: 'Сақталған үзінділер',
            empty: 'Бетбелгілер жоқ',
            emptySubtitle: 'Қызықты үзінділерді сақтаңыз, кейін оралу үшін',
            explore: 'Үзінділерді табу',
            remove: 'Бетбелгіден жою',
            removed: 'Бетбелгіден жойылды',
            loading: 'Бетбелгілер жүктелуде...',
            loadError: 'Бетбелгілерді жүктеу қатесі',
            noDescription: 'Сипаттама жоқ',
            error: 'Қате',
            bookmarksCount: 'Бетбелгілер',
            likesCount: 'Лайктар',
            topLanguage: 'Топ тіл',
            searchPlaceholder: 'Бетбелгілерде іздеу...',
            allLanguages: 'Барлық тілдер',
            byDate: 'Күні бойынша',
            byLikes: 'Лайктар бойынша',
            byTitle: 'Атауы бойынша',
            found: 'Табылды',
            nothingFound: 'Ештеңе табылмады',
        },
        // Страница Trending
        trending: {
            title: 'Трендтер',
            subtitle: 'Танымал үзінділер',
            hot: 'HOT',
            searchPlaceholder: 'Трендтерден іздеу...',
        },
        // Страница Notifications
        notifications: {
            title: 'Хабарламалар',
            allRead: 'Барлығы оқылды',
            unread: 'оқылмаған',
            markAllRead: 'Барлығын оқу',
            empty: 'Хабарламалар жоқ',
            emptySubtitle: 'Мұнда лайктар, пікірлер және жазылымдар туралы хабарламалар пайда болады',
            liked: 'постыңызды ұнатты',
            commented: 'постыңызға пікір қалдырды',
            followed: 'сізге жазылды',
            mentioned: 'сізді атап өтті',
            replied: 'пікіріңізге жауап берді',
            newPost: 'жаңа пост жариялады',
            loading: 'Жүктелуде...',
            allMarkedRead: 'Барлық хабарламалар оқылды',
            updateError: 'Жаңарту қатесі',
            explorePosts: 'Посттарды зерттеу',
            total: 'Барлығы',
            unreadCount: 'Оқылмаған',
            today: 'Бүгін',
            justNow: 'жаңа ғана',
        },
        // Страница Profile
        profile: {
            title: 'Профиль',
            editProfile: 'Өңдеу',
            posts: 'Посттар',
            followers: 'Жазылушылар',
            following: 'Жазылымдар',
            joined: 'Қосылды',
            noPosts: 'Әзірге посттар жоқ',
            createFirst: 'Алғашқы үзіндіңізді жасаңыз',
            createPost: 'Пост жасау',
        },
        // Страница Settings
        settings: {
            title: 'Баптаулар',
            subtitle: 'Аккаунт пен параметрлерді басқару',
            tabs: {
                profile: 'Профиль',
                appearance: 'Сыртқы көрініс',
                notifications: 'Хабарламалар',
                account: 'Аккаунт',
            },
            // Профиль
            profilePhoto: 'Профиль суреті',
            photoHint: 'JPG, PNG немесе GIF. Максимум 2MB.',
            removePhoto: 'Суретті жою',
            displayName: 'Көрсетілетін ат',
            username: 'Пайдаланушы аты',
            usernameHint: 'Пайдаланушы атын өзгерту мүмкін емес',
            emailHint: 'Email өзгерту мүмкін емес',
            bio: 'Өзіңіз туралы',
            bioPlaceholder: 'Өзіңіз туралы айтыңыз...',
            characters: 'таңба',
            location: 'Орналасқан жер',
            website: 'Веб-сайт',
            github: 'GitHub',
            profileSaved: 'Профиль сақталды!',
            // Внешний вид
            interfaceLanguage: 'Интерфейс тілі',
            chooseLanguage: 'Қалаған тілді таңдаңыз',
            theme: 'Безендіру тақырыбы',
            chooseTheme: 'Түс схемасын таңдаңыз',
            themeLight: 'Жарық',
            themeDark: 'Қараңғы',
            themeSystem: 'Жүйелік',
            codeTheme: 'Код тақырыбы',
            codeThemeHint: 'Код блоктары үшін синтаксис бөлектеу',
            codeFont: 'Код қаріпі',
            codeFontHint: 'Кодты көрсету қаріпі',
            fontSize: 'Қаріп өлшемі',
            fontSizeHint: 'Код редакторындағы қаріп өлшемі',
            preview: 'Алдын ала қарау',
            lineNumbers: 'Жол нөмірлері',
            lineNumbersHint: 'Кодта жол нөмірлерін көрсету',
            wordWrap: 'Жолды тасымалдау',
            wordWrapHint: 'Ұзын код жолдарын тасымалдау',
            compactMode: 'Ықшам режим',
            compactModeHint: 'Көбірек мазмұн үшін шегіністерді азайту',
            saveSettings: 'Баптауларды сақтау',
            settingsSaved: 'Баптаулар сақталды!',
            // Уведомления
            emailNotifications: 'Email хабарламалар',
            pushNotifications: 'Push хабарламалар',
            enableAll: 'Барлығын қосу',
            disableAll: 'Барлығын өшіру',
            notifyLikes: 'Лайктар',
            notifyLikesHint: 'Біреу постыңызды ұнатқанда',
            notifyComments: 'Пікірлер',
            notifyCommentsHint: 'Біреу пікір қалдырғанда',
            notifyFollowers: 'Жаңа жазылушылар',
            notifyFollowersHint: 'Біреу сізге жазылғанда',
            notifyMentions: 'Атап өтулер',
            notifyMentionsHint: 'Сізді атап өткенде',
            notifyDigest: 'Апталық дайджест',
            notifyDigestHint: 'Аптаның ең жақсы посттары',
            notificationsSaved: 'Хабарлама баптаулары сақталды!',
            // Аккаунт
            changePassword: 'Құпия сөзді өзгерту',
            currentPassword: 'Ағымдағы құпия сөз',
            newPassword: 'Жаңа құпия сөз',
            confirmNewPassword: 'Құпия сөзді растаңыз',
            passwordsMatch: 'Құпия сөздер сәйкес келеді',
            passwordStrength: {
                weak: 'Әлсіз',
                fair: 'Орташа',
                good: 'Жақсы',
                strong: 'Күшті',
                veryStrong: 'Өте күшті',
            },
            passwordRequirements: {
                minLength: 'Кемінде 8 таңба',
                uppercase: 'Бір бас әріп',
                lowercase: 'Бір кіші әріп',
                number: 'Бір сан',
                special: 'Бір арнайы таңба',
            },
            updatePassword: 'Құпия сөзді өзгерту',
            passwordUpdated: 'Құпия сөз сәтті өзгертілді!',
            twoFactorAuth: 'Екі факторлы аутентификация',
            twoFactorHint: 'Аккаунтыңызға қосымша қауіпсіздік деңгейін қосыңыз.',
            enable2FA: '2FA қосу',
            sessions: 'Сессиялар',
            logoutAll: 'Барлық құрылғылардан шығу',
            logoutAllHint: 'Барлық құрылғылардағы аккаунттан шығу.',
            exportData: 'Деректерді экспорттау',
            exportDataHint: 'Деректеріңіздің көшірмесін жүктеңіз: профиль, бетбелгілер және посттар.',
            exportButton: 'Деректерді экспорттау',
            exported: 'Деректер экспортталды!',
            dangerZone: 'Қауіпті аймақ',
            deleteAccount: 'Аккаунтты жою',
            deleteAccountHint: 'Аккаунтты жойғаннан кейін барлық деректеріңіз қайтымсыз жойылады.',
            deleteAccountButton: 'Аккаунтты жою',
            deleteConfirmTitle: 'Сенімдісіз бе?',
            deleteConfirmText: 'Бұл әрекетті қайтару мүмкін емес. Барлық деректеріңіз, посттарыңыз және бетбелгілеріңіз мәңгілікке жойылады.',
        },
        // Widgets
        widgets: {
            trendingNow: 'Қазір трендте',
            topContributors: 'Үздік авторлар',
            viewProfile: 'Профиль',
            quickActions: 'Жылдам әрекеттер',
            newSnippet: 'Жаңа үзінді',
            community: 'Қауымдастық',
            statistics: 'Статистика',
            totalLikes: 'Барлық лайктар',
            commentsCount: 'Пікірлер',
            viewsCount: 'Қаралымдар',
            viewAll: 'Барлығы',
            aboutUs: 'Біз туралы',
            terms: 'Шарттар',
            privacy: 'Құпиялылық',
            help: 'Көмек',
        },
        // Жаңа пост
        newPost: {
            title: 'Жаңа пост',
            subtitle: 'Қауымдастықпен кодпен бөлісіңіз',
            titleLabel: 'Тақырып',
            titlePlaceholder: 'Мысалы: Debounce үшін React хук',
            descriptionLabel: 'Сипаттама',
            descriptionPlaceholder: 'Кодыңыздың не істейтінін қысқаша сипаттаңыз...',
            languageLabel: 'Тіл',
            selectLanguage: 'Тілді таңдаңыз',
            filenameLabel: 'Файл атауы',
            filenamePlaceholder: 'Мысалы: useDebounce.ts',
            codeLabel: 'Код',
            editor: 'Редактор',
            preview: 'Алдын ала қарау',
            previewPlaceholder: '// Алдын ала қарау осында пайда болады...',
            codePlaceholder: '// Кодыңызды осында қойыңыз...',
            tagsLabel: 'Тегтер',
            tagsMax: 'макс. 5',
            addTagPlaceholder: 'Тегтерді қосыңыз (Enter басыңыз)',
            suggestions: 'Ұсыныстар:',
            public: 'Жалпыға қолжетімді',
            private: 'Жеке',
            draft: 'Жоба',
            draftSaved: 'Жоба сақталды',
            publish: 'Жариялау',
            publishing: 'Жариялануда...',
            create: 'Жасау',
            published: 'Пост жарияланды!',
            loginRequired: 'Аккаунтқа кіріңіз',
        },
        // Лента
        feed: {
            title: 'Лента',
            subtitle: 'Соңғы жарияланымдар',
            refresh: 'Жаңарту',
            loadingPosts: 'Посттар жүктелуде...',
            tryAgain: 'Қайталап көру',
            noPosts: 'Әзірге посттар жоқ',
            beFirst: 'Қауымдастықпен кодын бөлісетін алғашқы адам болыңыз!',
            createPost: 'Пост жасау',
            showMore: 'Көбірек көрсету',
            loading: 'Жүктелуде...',
        },
        // Іздеу
        search: {
            users: 'Пайдаланушылар',
            posts: 'Посттар',
            noResults: 'Ештеңе табылмады',
        },
        // Тексеру
        validation: {
            required: 'міндетті',
            minChars: 'Кемінде 3 таңба',
            onlyLatinAndUnderscore: 'Тек әріптер, сандар және _',
            invalidEmail: 'Қате email',
            passwordNotMeet: 'Құпия сөз талаптарға сай емес',
            acceptTerms: 'Шарттарды қабылдау қажет',
            enterTitle: 'Тақырып енгізіңіз',
            enterFilename: 'Файл атауын енгізіңіз',
            selectLanguage: 'Тілді таңдаңыз',
            enterCode: 'Код енгізіңіз',
            loginError: 'Кіру қатесі',
            accountCreated: 'Аккаунт жасалды!',
            commentEmpty: 'Пікір бос болмауы керек',
            loginToComment: 'Пікір қалдыру үшін кіріңіз',
            commentAdded: 'Пікір қосылды!',
            commentAddError: 'Пікір қосу қатесі',
            replyAdded: 'Жауап қосылды!',
            replyError: 'Жауап жіберу қатесі',
            commentDeleted: 'Пікір жойылды',
            deleteError: 'Жою қатесі',
        },
        // Футер
        footer: {
            about: 'Біз туралы',
            privacy: 'Құпиялылық',
            terms: 'Шарттар',
            contact: 'Байланыс',
            help: 'Көмек',
            copyright: '© 2025 GitForum',
        },
        // Бейджар
        badges: {
            fast: 'Жылдам',
            secure: 'Қауіпсіз',
            modern: 'Заманауи',
            live: 'Live',
            ready: 'Дайын',
            secureLogin: 'Қауіпсіз кіру',
            freeRegistration: 'Тегін тіркелу',
            haveAccount: 'Аккаунтыңыз бар ма?',
            instantAuth: 'Лезде авторизация',
            secureEncryption: 'Қауіпсіз шифрлау',
            oauthIntegration: 'OAuth 2.0 интеграциясы',
            createProfile: 'Профиль жасаңыз',
            chooseUsername: 'Бірегей username таңдаңыз',
            shareCode: 'Кодпен бөлісіңіз',
            publishSnippets: 'Үзінділерді жариялаңыз',
            communicate: 'Қарым-қатынас жасаңыз',
            findLikeminded: 'Ойластастарды табыңыз',
            programmingLanguages: 'бағдарламалау тілдері',
        },
        // Пікірлер
        comments: {
            title: 'Пікірлер',
            reply: 'Жауап беру',
            delete: 'Жою',
            cancel: 'Болдырмау',
            send: 'Жіберу',
            writePlaceholder: 'Пікір жазыңыз...',
            replyTo: 'Жауап беру',
            noneYet: 'Әзірге пікірлер жоқ',
            beFirst: 'Алғашқы болыңыз!',
            loginPrompt: 'Пікір қалдыру үшін кіріңіз',
            login: 'Кіру',
        },
        // Сүзгілер
        filters: {
            searchPlaceholder: 'Үзінділер, тегтер іздеу...',
            activeTags: 'Белсенді тегтер:',
            clear: 'Тазалау',
            tags: 'Тегтер',
            categories: 'Санаттар',
            period: 'Кезең',
            sort: 'Сұрыптау',
            today: 'Бүгін',
            week: 'Апта',
            month: 'Ай',
            allTime: 'Барлық уақыт',
            byLikes: 'Лайктар бойынша',
            byComments: 'Пікірлер бойынша',
            byViews: 'Қаралымдар бойынша',
            recent: 'Жаңалар',
            all: 'Барлығы',
        },
        // Пост
        post: {
            by: 'авторы',
            copyCode: 'Кодты көшіру',
            codeCopied: 'Код көшірілді!',
            comments: 'Пікірлер',
            addComment: 'Пікір жазу...',
            sendComment: 'Жіберу',
            noComments: 'Әзірге пікірлер жоқ',
            beFirst: 'Пікір қалдырған алғашқы адам болыңыз!',
            deleteComment: 'Пікірді жою',
            editComment: 'Өңдеу',
        },
        // Время
        time: {
            justNow: 'қазір ғана',
            minutesAgo: 'м бұрын',
            hoursAgo: 'сағ бұрын',
            daysAgo: 'к бұрын',
        },
        // Басты бет
        landing: {
            tagline: 'Кодпен бөлісіңіз, скриншоттармен емес',
            heroTitle: 'Код',
            heroTitleHighlight: 'алмасу форумы',
            heroDescription: 'Әдемі код үзінділерімен бөлісіңіз, трендті шешімдерді табыңыз және бүкіл әлемдегі әзірлеушілермен байланысыңыз.',
            getStarted: 'Тегін бастау',
            features: {
                title: 'Кодпен жұмыс істеуге қажет барлығы',
                subtitle: 'Әзірлеушілер үшін әзірлеушілер жасаған. Барлық құралдар бір жерде.',
                syntaxHighlighting: 'Синтаксис бөлектеу',
                syntaxHighlightingDesc: 'VS Code тақырыптарымен 50+ тіл үшін әдемі код рендерингі',
                trendingSnippets: 'Трендті үзінділер',
                trendingSnippetsDesc: 'Қауымдастықтағы ең танымал үзінділерді табыңыз',
                smartTags: 'Ақылды тегтер',
                smartTagsDesc: 'Кодты тіл, фреймворк немесе тақырып бойынша ұйымдастырыңыз',
                bookmarks: 'Бетбелгілер',
                bookmarksDesc: 'Жылдам қол жеткізу үшін сүйікті үзінділерді сақтаңыз',
                easySharing: 'Оңай бөлісу',
                easySharingDesc: 'Бір басумен кодпен бөлісіңіз',
                powerfulSearch: 'Қуатты іздеу',
                powerfulSearchDesc: 'Жетілдірілген іздеу арқылы дәл қажетін табыңыз',
            },
            howItWorks: {
                title: 'Қалай жұмыс істейді',
                subtitle: 'Кодты жариялаудың үш қарапайым қадамы',
                step1: 'Жасаңыз',
                step1Desc: 'Толық синтаксис бөлектеуімен код жазыңыз немесе қойыңыз',
                step2: 'Бөлісіңіз',
                step2Desc: 'Үзіндіні жариялаңыз және қауымдастықпен бөлісіңіз',
                step3: 'Зерттеңіз',
                step3Desc: 'Трендтерді зерттеңіз, басқалардан үйреніңіз және бірге өсіңіз',
            },
            stats: {
                developers: 'Әзірлеушілер',
                snippets: 'Код үзінділері',
                languages: 'Тілдер',
                linesShared: 'Жариялаған жолдар',
            },
            cta: {
                joinDevelopers: '50 000+ әзірлеушіге қосылыңыз',
                readyToShare: 'Кодпен бөлісуге дайынсыз ба?',
                signUpToday: 'Бүгін тіркеліңіз және әдемі үзінділерді жариялай бастаңыз.',
                createAccount: 'Тегін аккаунт жасау',
            },
            footer: {
                about: 'Біз туралы',
                privacy: 'Құпиялылық',
                terms: 'Шарттар',
                contact: 'Байланыс',
                copyright: '© 2025 GitForum. Барлық құқықтар қорғалған.',
            },
        },
        // Страница настроек
        settingsPage: {
            // Account
            changePassword: 'Құпия сөзді өзгерту',
            updateAccountPassword: 'Аккаунт құпия сөзін жаңартыңыз',
            currentPassword: 'Ағымдағы құпия сөз',
            newPassword: 'Жаңа құпия сөз',
            confirmPassword: 'Құпия сөзді растаңыз',
            passwordsMatch: 'Құпия сөздер сәйкес келеді',
            enterCurrentPassword: 'Ағымдағы құпия сөзді енгізіңіз',
            enterNewPassword: 'Жаңа құпия сөзді енгізіңіз',
            confirmPasswordRequired: 'Құпия сөзді растаңыз',
            passwordsDontMatch: 'Құпия сөздер сәйкес келмейді',
            minChars: 'Кемінде 8 таңба',
            fixErrors: 'Қателерді түзетіңіз',
            passwordChanged: 'Құпия сөз өзгертілді!',
            checkCurrentPassword: 'Ағымдағы құпия сөзді тексеріңіз',
            saving: 'Сақтау...',
            changePasswordBtn: 'Құпия сөзді өзгерту',
            // Password strength
            weak: 'Әлсіз',
            medium: 'Орташа',
            good: 'Жақсы',
            strong: 'Күшті',
            veryStrong: 'Өте күшті',
            min8chars: 'Кемінде 8 таңба',
            uppercase: 'Бас әріп',
            lowercase: 'Кіші әріп',
            digit: 'Сан',
            special: 'Арнайы таңба',
            // 2FA
            twoFactor: 'Екі факторлы аутентификация',
            additionalSecurity: 'Қосымша қорғаныс',
            twoFactorDesc: 'Қосымша қауіпсіздік деңгейін қосыңыз.',
            enable2FA: '2FA қосу',
            twoFactorFuture: '2FA болашақ жаңартуларда қол жетімді болады',
            // Connected accounts
            connectedAccounts: 'Байланысқан аккаунттар',
            oauthProviders: 'OAuth провайдерлер',
            notConnected: 'Қосылмаған',
            disconnect: 'Ажырату',
            connect: 'Қосу',
            disconnected: 'ажыратылды',
            disconnectError: 'Ажырату қатесі',
            disconnectAccountError: 'Аккаунтты ажырату қатесі',
            // Sessions
            sessions: 'Сессиялар',
            sessionManagement: 'Кіруді басқару',
            logoutAllDesc: 'Барлық құрылғылардан шығу.',
            logoutAllDevices: 'Барлық құрылғылардан шығу',
            loggedOutAll: 'Сіз барлық құрылғылардан шықтыңыз',
            logoutError: 'Шығу қатесі',
            // Export
            exportData: 'Деректерді экспорттау',
            downloadDataCopy: 'Деректердің көшірмесін жүктеңіз',
            exporting: 'Экспорттау...',
            exportDataBtn: 'Деректерді экспорттау',
            dataExported: 'Деректер экспортталды!',
            exportError: 'Экспорт қатесі',
            // Danger zone
            dangerZone: 'Қауіпті аймақ',
            irreversibleActions: 'Қайтарылмайтын әрекеттер',
            deleteAccountWarning: 'Аккаунтты жойғаннан кейін барлық деректер біржола жойылады.',
            deleteAccount: 'Аккаунтты жою',
            areYouSure: 'Сенімдісіз бе?',
            deleteConfirmation: 'Бұл әрекетті қайтару мүмкін емес. Барлық деректер мәңгілікке жойылады.',
            cancel: 'Болдырмау',
            deleteFuture: 'Аккаунтты жою болашақ жаңартуларда қол жетімді болады',
            // Appearance
            interfaceLanguage: 'Интерфейс тілі',
            selectPreferredLanguage: 'Қалаған тілді таңдаңыз',
            codeTheme: 'Код тақырыбы',
            syntaxHighlighting: 'Синтаксисті бөлектеу',
            codeFont: 'Код шрифті',
            monospacedFont: 'Моноширинді шрифт',
            fontSize: 'Шрифт өлшемі',
            fontSizeInCode: 'Кодтағы мәтін өлшемі',
            lineHeight: 'Жолдар арасы',
            spaceBetweenLines: 'Жолдар арасындағы аралық',
            compact: 'Компактті',
            spacious: 'Кең',
            editorSettings: 'Редактор параметрлері',
            additionalOptions: 'Қосымша опциялар',
            lineNumbers: 'Жол нөмірлері',
            leftOfCode: 'Кодтың сол жағында',
            wordWrap: 'Сөздерді тасымалдау',
            autoWrap: 'Автоматты тасымалдау',
            preview: 'Алдын ала қарау',
            codePreview: 'Код қалай көрінеді',
            settingsSaved: 'Параметрлер сақталды!',
            saveSettings: 'Параметрлерді сақтау',
            // Notifications
            emailNotifications: 'Email хабарландырулар',
            notificationsToEmail: 'Поштаға хабарландырулар',
            pushNotifications: 'Push хабарландырулар',
            browserNotifications: 'Браузер хабарландырулары',
            on: 'Қосу',
            off: 'Өшіру',
            likes: 'Лайктар',
            whenLiked: 'Біреу сіздің постыңызды лайктағанда',
            comments: 'Пікірлер',
            whenCommented: 'Біреу пікір қалдырғанда',
            newFollowers: 'Жаңа жазылушылар',
            whenFollowed: 'Біреу сізге жазылғанда',
            mentions: 'Атаулар',
            whenMentioned: 'Сізді атаған кезде',
            weeklyDigest: 'Апталық дайджест',
            weeklyDigestDesc: 'Аптаның үздік посттары',
            notificationsSaved: 'Хабарландыру параметрлері сақталды!',
            // Profile
            profilePhoto: 'Профиль суреті',
            photoFormats: 'JPG, PNG немесе GIF. Максимум 5MB.',
            cancelUpload: 'Болдырмау',
            displayName: 'Көрсетілетін ат',
            username: 'Пайдаланушы аты',
            cannotChange: 'Өзгерту мүмкін емес',
            aboutMe: 'Мен туралы',
            tellAboutYourself: 'Өзіңіз туралы айтыңыз...',
            location: 'Орналасқан жері',
            cityCountry: 'Қала, Ел',
            website: 'Веб-сайт',
            nameRequired: 'Ат міндетті',
            bioMaxLength: 'Био 160 таңбадан аспауы керек',
            urlFormat: 'URL http:// немесе https:// деп басталуы керек',
            fixErrorsBeforeSave: 'Сақтау алдында қателерді түзетіңіз',
            profileSaved: 'Профиль сақталды!',
            profileSaveError: 'Профильді сақтау қатесі',
            saveChanges: 'Өзгерістерді сақтау',
            uploadingAvatar: 'Аватар жүктелуде...',
            avatarUpdated: 'Аватар жаңартылды!',
            fileTooLarge: 'Файл тым үлкен. Максимум 5MB.',
            selectImage: 'Суретті таңдаңыз (JPG, PNG, GIF, WebP)',
            avatarUploadError: 'Аватар жүктеу қатесі',
        },
        // Тексты страниц
        pages: {
            // Settings page
            settings: {
                title: 'Параметрлер',
                subtitle: 'Аккаунт пен қалауларды басқару',
                tabDescriptions: {
                    profile: 'Ат, аватар, био',
                    appearance: 'Тема, тіл',
                    notifications: 'Email, push',
                    account: 'Құпия сөз, қауіпсіздік',
                },
            },
            // Trending page
            trending: {
                howItWorks: 'Қалай жұмыс істейді',
                howItWorksDesc: 'Посттар танымалдылық бойынша сұрыпталады — лайктар, пікірлер және көрулер саны. HOT белгісі бар посттардың белсенділігі жоғары.',
                searchPlaceholder: 'Трендтерде іздеу...',
                loadingTrends: 'Трендтер жүктелуде...',
                loadError: 'Жүктеу қатесі',
                noTrendingPosts: 'Trending посттар жоқ',
                createFirstPost: 'Алғашқы постты жасаңыз!',
                changeFilters: 'Сүзгілерді өзгертіп көріңіз',
                found: 'Табылды',
                posts: 'Посттар',
                likes: 'Лайктар',
                views: 'Көрулер',
                noDescription: 'Сипаттама жоқ',
            },
            // Tags page
            tags: {
                totalTags: 'Барлық тегтер',
                totalPosts: 'Барлық посттар',
                topTag: 'Топ тег',
                popularTags: 'Танымал тегтер',
                loadingTags: 'Тегтер жүктелуде...',
                found: 'Табылды',
                tryAnotherSearch: 'Іздеу сұрауын өзгертіп көріңіз',
            },
            // Explore page
            explore: {
                noDescription: 'Сипаттама жоқ',
                errorLoading: 'Деректерді жүктеу қатесі',
                loading: 'Жүктелуде...',
                nothingFound: 'Ештеңе табылмады',
                noPosts: 'Әзірше посттар жоқ. Бірінші болыңыз!',
                tryChangeFilters: 'Сүзгілерді немесе іздеу сұрауын өзгертіп көріңіз',
                found: 'Табылды',
                thisWeek: 'Аптада',
                today: 'Бүгін',
            },
            // Post page
            post: {
                loadingPost: 'Пост жүктелуде...',
                postNotFound: 'Пост табылмады',
                maybeDeleted: 'Мүмкін ол жойылған',
                back: 'Оралу',
                backToFeed: 'Лентаға оралу',
                edit: 'Өзгерту',
                delete: 'Жою',
                codeCopied: 'Код көшірілді!',
                linkCopied: 'Сілтеме көшірілді!',
                loginToLike: 'Лайк басу үшін кіріңіз',
                loginToBookmark: 'Сақтау үшін кіріңіз',
                removedFromBookmarks: 'Бетбелгілерден алынды',
                addedToBookmarks: 'Бетбелгілерге қосылды',
                postDeleted: 'Пост жойылды',
                deleteError: 'Жою қатесі',
                copied: 'Көшірілді',
                copy: 'Көшіру',
                error: 'Қате',
                minutesAgo: 'мин бұрын',
                hoursAgo: 'сағ бұрын',
                daysAgo: 'күн бұрын',
            },
            // Profile page
            profile: {
                share: 'Бөлісу',
                settings: 'Параметрлер',
                linkCopied: 'Сілтеме көшірілді!',
                joined: '',
                posts: 'Посттар',
                followers: 'Жазылушылар',
                following: 'Жазылғандар',
                likes: 'Лайктар',
                views: 'Көрулер',
                postsTab: 'Посттар',
                bookmarksTab: 'Бетбелгілер',
                noDescription: 'Сипаттама жоқ',
                noPosts: 'Әзірше посттар жоқ',
                createFirstSnippet: 'Алғашқы үзіндіңізді жасаңыз және қауымдастықпен бөлісіңіз',
                createPost: 'Пост жасау',
                noBookmarks: 'Бетбелгілер жоқ',
                saveSnippets: 'Жылдам қол жеткізу үшін пайдалы үзінділерді сақтаңыз',
                findSnippets: 'Үзінділерді табу',
                loading: 'Жүктелуде...',
            },
            // User page
            user: {
                userNotFound: 'Пайдаланушы табылмады',
                backToFeed: 'Оралу',
                follow: 'Жазылу',
                unfollow: 'Жазылымнан шығу',
                message: 'Хабарлама',
                share: 'Бөлісу',
                report: 'Шағымдану',
                joined: '',
                posts: 'Посттар',
                followers: 'Жазылушылар',
                following: 'Жазылғандар',
                likes: 'Лайктар',
                views: 'Көрулер',
                postsTab: 'Посттар',
                noPosts: 'Әзірше посттар жоқ',
                userHasNoPosts: 'Пайдаланушы әлі ешқандай пост жарияламаған',
                noDescription: 'Сипаттама жоқ',
                loading: 'Жүктелуде...',
                settings: 'Параметрлер',
            },
        },
    },
}

// Типы для переводов
type TranslationKeys = typeof translations.ru

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: TranslationKeys
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

interface LanguageProviderProps {
    children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
    const [language, setLanguageState] = useState<Language>('ru')

    useEffect(() => {
        // Загружаем сохранённый язык из localStorage
        const saved = localStorage.getItem('gitforum-language') as Language
        if (saved && (saved === 'ru' || saved === 'kk')) {
            setLanguageState(saved)
        }
    }, [])

    const setLanguage = (lang: Language) => {
        setLanguageState(lang)
        localStorage.setItem('gitforum-language', lang)
    }

    const t = translations[language]

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
