# Generated by Django 5.2.8 on 2025-12-15 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2000, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('language', models.CharField(choices=[('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('python', 'Python'), ('rust', 'Rust'), ('go', 'Go'), ('java', 'Java'), ('csharp', 'C#'), ('cpp', 'C++'), ('c', 'C'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('shell', 'Shell/Bash'), ('ruby', 'Ruby'), ('php', 'PHP'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('dart', 'Dart'), ('yaml', 'YAML'), ('json', 'JSON'), ('markdown', 'Markdown'), ('other', 'Другой')], max_length=50, verbose_name='Язык')),
                ('code', models.TextField(verbose_name='Код')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментарии')),
                ('bookmarks_count', models.PositiveIntegerField(default=0, verbose_name='В закладках')),
                ('forks_count', models.PositiveIntegerField(default=0, verbose_name='Форки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Цвет (HEX)')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Использований')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-usage_count', 'name'],
            },
        ),
    ]
