# Generated by Django 5.2.8 on 2025-12-15 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField(verbose_name='Номер ревизии')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('code', models.TextField(verbose_name='Код')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('commit_message', models.CharField(blank=True, max_length=500, verbose_name='Сообщение об изменении')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='posts.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Ревизия поста',
                'verbose_name_plural': 'Ревизии постов',
                'ordering': ['-revision_number'],
                'unique_together': {('post', 'revision_number')},
            },
        ),
    ]
